// Code generated by goctl. DO NOT EDIT.
package types

type TitokLive struct {
	OpenUrl    string `json:"open_url"`
	Info       string `json:"info"`
	Name       string `json:"name"`
	Id         int64  `db:"id"`
	CreateTime int64  `db:"create_time"`
	OpenTime int64    `db:"open_string"`
	IsNeedFork int64
}

type SaveLiveReq struct {
	OpenUrl string `json:"open_url"`
	Info    string `json:"info"`
	Name    string `json:"name"`
}

type SaveLiveResp struct {
	Id int64 `json:"id"`
	Content string `json:"content"`
}

type FetchLiveResp struct {
	List []TitokLive `json:"list"`
}

type SaveResultReq struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type SaveResultResp struct {
	Content string `json:"content"`
}
type RedPacket struct {
	Name      string `json:"name"`
	JoinCount string `json:"joinCount"`
	Time      string `json:"time"`
	JoinCondition []string `json:"joinCondition"`
	CT            string   `json:"ct"` 
}
type ReceiveReq struct {
	Id int64 `json:"Id"`
}
