// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	tiktok "looklook/app/tiktok/cmd/api/internal/handler/tiktok"
	"looklook/app/tiktok/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/save",
				Handler: tiktok.SaveLiveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/fetch",
				Handler: tiktok.FetchHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: tiktok.PingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/saveResult",
				Handler: tiktok.SaveResultHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ws",
				Handler:tiktok.WsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/tiktok/v1"),
	)
	server.AddRoutes(
		[]rest.Route{
			
			  {
						Method:http.MethodPost,
						  Path:"/receive",
					  Handler:tiktok.ReceiveHandler(serverCtx),
			   
			  },
	   },
		  rest.WithPrefix("/tiktok/v1"),
 )    
}
